### ISSUE TITLE
Cannot run application without doing a brew install opencv@4

### ISSUE THREAD

**Issue by arpwal** [fakob/MoviePrint_v004#14]
Hey @fakob, I was trying to test the application with some of my changes and run the packaged application on a mac. 

However, the app shows a blank white screen. After some debugging, I found that `opencv-build` dependency in `app/node-modules/` does not have the opencv dylibs. 

I think you did resolve a similar issue with your changes [here](https://github.com/justadudewhohacks/opencv4nodejs/commit/01aadd48a937d9d19373c0d0dc32a2bc2d149a09). I also did follow the [issue you filed](https://github.com/justadudewhohacks/opencv4nodejs/issues/204), however I am currently able to resolve the opencv dependency. 

However, when I download the app that you have on the website, it works fine without having to install opencv on the users machine (the `opencv-build` directory does have the dylibs there). 

Any idea what I might be missing out here?

**Comment by fakob** [comment]
Hi @arpwal

It has been a while since I did a clean install so it is a bit of a guess work.

As far as I remember, I did not get opencv 4 to work. I don't remember if this was an issue with packaging though. I am still [using opencv 3.4.6](https://github.com/fakob/MoviePrint_v004#mac-setup) and my [opencv.js script](https://github.com/fakob/MoviePrint_v004/blob/master/scripts/opencv.js) which fixes the dependencies might not work properly with opencv 4.  

This is also the reason why I have not upgraded opencv4nodejs to the newest version. See issue [here](https://github.com/justadudewhohacks/opencv4nodejs/issues/645), unfortunately I am stuck there.

What do the logs say when you start the application in debug mode (Application menu -> View -> Restart in debug mode and then check the developer tools console logs of the different renderers. See Debug menu)?
What is the output when you run `yarn opencv`? Is the copying and relinking successful?

Sorry, it is a bit of a guess work. I had spent quite some time on it to make it work. Unfortunately it is not straight forward.

**Comment by arpwal** [comment]
Hey @fakob 

Thanks for getting back to me. I am just running `yarn install` at this point, and that seems to be failing for me with auto_build on. 

[Logs for running `yarn install` in the parent directory](https://github.com/fakob/MoviePrint_v004/files/4639973/install-log-main.txt)

Also, I'm using the following environment variables: 

```bash
export OPENCV4NODEJS_DISABLE_AUTOBUILD=0
export OPENCV4NODEJS_AUTOBUILD_OPENCV_VERSION=3.4.6
export NODE_GYP_FORCE_PYTHON=/usr/bin/python
```

I'm using MacOS Catalina 10.15.4, 16gb memory, if that helps.

I updated the OpenCV version as per your suggestion too to 3.4.6

The `opencv.js` script seems to look good, just that the that `/app/node_nodules/opencv-build/opencv/build/lib/` is empty at this point still (which is referenced by the `opencv.js` script. 

Any idea what is going on?

**Comment by fakob** [comment]
Hi @arpwal 

The error you are getting `fatal error: 'opencv2/core.hpp' file not found` seems to indicate that opencv4nodejs@5.x version was installed, which unfortunately does not work at the moment. See previously linked [issue](https://github.com/justadudewhohacks/opencv4nodejs/issues/645).

So I would suggest to downgrade opencv4nodejs. The latest version which worked for me is [4.17.0](https://github.com/justadudewhohacks/opencv4nodejs/releases/tag/4.17.0).

Sorry, I should probably change the app/package.json so it does not automatically install the newest version.

**Comment by arpwal** [comment]
Hey @fakob 

Good point.. I did force the package json to install opencv4nodejs v4.17.0. [package.json from opencv4nodejs](https://github.com/fakob/MoviePrint_v004/files/4640671/opencv4nodejs-package-json.txt) in the `app/node_modules` dir.

I'm still getting the same error: `fatal error: 'opencv2/core.hpp' file not found`. [logs](https://github.com/fakob/MoviePrint_v004/files/4640674/install-4.17.0-opencv4nodejs.txt)

What version of `node-gyp` do you have installed?

**Comment by fakob** [comment]
That is strange, I can not remember every having this error with my usual setup.
Did you do a clean install?
Another thing, I don't think I had ever used environment variables to override opencv4nodejs settings. Could you try without?

I currently do not have access to my build machine, but according to the submitted yarn.lock file I was using `node-gyp: 6.1.0`.

**Comment by arpwal** [comment]
Yeah the environment variables seemed to cause some problems. 
After removing them, I moved a little forward but got another set of errors: [install.log.trim](https://github.com/fakob/MoviePrint_v004/files/4640963/install.log.trim.txt)

snippet from the logs --

```bash
[ 78%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/torch/THDiskFile.cpp.o
[ 78%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/torch/THFile.cpp.o
[ 78%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/torch/THGeneral.cpp.o
[ 78%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/torch/torch_importer.cpp.o
[ 78%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/layers/layers_common.avx.cpp.o
[ 78%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/layers/layers_common.avx2.cpp.o
[ 78%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/layers/layers_common.avx512_skx.cpp.o
[ 78%] Linking CXX shared library ../../lib/libopencv_dnn.dylib
[ 78%] Built target opencv_dnn
make: *** [all] Error 2
ERR! child process exited with code 2 (for more info, set '--loglevel silly')
  stackTrace=
```

Thoughts?

**Comment by fakob** [comment]
Ahh, shoot. I have never built it on Catalina. Not sure if this is the problem, but currently I would not know what else is. To be honest, the building of native modules I never fully understood, so there was lots of trial and error for me to make it work.
I will try to find some time in the coming week to set up a virtual catalina machine and see how far I get with building it from scratch.
I am sorry that I do not have any more suggestions at the moment.

**Comment by arpwal** [comment]
Oh no! Please let me know if you find something new. I've tried the following things: 

- tried with python3.x & python2.7 none worked,
- tried installing opencv3 on catalina from source, following [this blog](https://medium.com/analytics-vidhya/installing-opencv-3-from-source-on-macos-catalina-cefc71e2fda), and that went fine,
- also, as I mentioned before -- opencv4nodejs (5.3.x) worked fine when installed with `brew install opencv@4`

Inspired by your `scripts/opencv.js`, do you think we could repurpose that script to use the libs generated in `/usr/local/opencv/` and use them while packaging the app in the `dependencies` folder?

**Comment by fakob** [comment]
* With python3 I had also never worked for me.
* What cmake version do you have installed?
* The script could work. You could try changing the [opencvLibDir variable](https://github.com/fakob/MoviePrint_v004/blob/e04da819d735fa446037d6252d2408605d302034/scripts/opencv.js#L60)

**Comment by fakob** [comment]
Hi @arpwal 
I have now made a clean install on a catalina virtual machine. I ran into some issues, but got them resolved and could build and package the app doing the following steps
* install brew
  * installs command line tools for xcode
* brew install yarn
* brew install cmake
* install node [12.8.1 with installer](https://nodejs.org/download/release/v12.8.1/node-v12.8.1.pkg)
this I had forgotten to mention, though the error messages you had gotten pointed to something else. Having the wrong node version usually was only an issue for the face-api.js dependency tfjs-node. I have to update the readme
* git clone --depth=1 https://github.com/fakob/MoviePrint_v004.git MoviePrint_v004
* Get the original weights files from [face-api.js](https://github.com/justadudewhohacks/face-api.js/tree/master/weights) and replace the ones in /resources/weights
Somehow one of the weights in my repo is corrupted. Will push an update soon.
* cd MoviePrint_v004
* cd app
* yarn
running yarn separately for the native packages should not be necessary as it should be called from the top level yarn, but it seemed to me that I get different results
* cd ..
* yarn
* yarn includeInDist
copy fonts and weights into dist folder
* yarn dev
test run in dev
* yarn package-dir
run package only creating the app file

Hope that helps

**Comment by arpwal** [comment]
Hey @fakob -- thanks for the detailed installation steps. 

I was doing the same steps as you wrote in detail above, however I still seem to land into the same error. Probably my machine setup is borked (I was using the opencv4nodejs package with opencv4 from brew before)? I'll give it a try on a mac vm to see if that points to a possible solution. 

Thanks for trying to debug this with me!
