### ISSUE TITLE
Styling Colors doesn{t keep between sessions...

### ISSUE THREAD

**Issue by nanohtpc** [fakob/MoviePrint_v004#15]
Styling Colors doesn{t keep between sessions...

**Comment by fakob** [comment]
Hi @nanohtpc 
I have tried setting background color for frame info and movieprint and both persisted when I restarted the app.
Please let me know what operating system and which app version you are using. Not sure where the problem could lie. Is that the only thing which does not persist?

**Comment by nanohtpc** [comment]
Latest version

Win10x64

The problem is in the styling option, i use 2 colors. RGB 255,0,0 and
128,0,128, but only shows results into the first one... seems that doesnt
update...

**Comment by fakob** [comment]
Hmm, that is strange. Here some questions:
* When you change other settings, are they kept after an app restart?
* Are your movies and MoviePrint selections kept after an app restart?

You could do a factory reset of the app.
Go to the Application menu -> View -> Reset application - CAREFUL this will remove all movies, MoviePrint selections and reset the settings!

**Comment by nanohtpc** [comment]
I input this....

but get that...

**Comment by fakob** [comment]
Hi @nanohtpc it seems that there is information missing in your replies. I assume that email replies do not allow attachments.

**Comment by nanohtpc** [comment]
Program : Pirple

[image: Screenshot (333).png]
Result :RED?????????????

[image: 01.12.20 - El Doctorcito de Santa Rosa Cercado 2020 -
Preview.mkv-MoviePrint-1.png]

**Comment by fakob** [comment]
@nanohtpc sorry, still no attachments visible.
