### ISSUE TITLE
Privacy policy?

### ISSUE THREAD

**Issue by friendlytherapist** [fakob/MoviePrint_v004#22]
What is your privacy policy? From the start your app requires a connection to google for fonts. Do you send or collect any information? Does the face detection send data to the cloud to be processed?

**Comment by fakob** [comment]
Hi @friendlytherapist 
MoviePrint does not collect any data. The fact that it connects to fonts.googleapis.com is correct. This comes from a dependency to semantic ui a ui framework. But that should be the only communication with the outside world. All work including detection is done in app.
Hope that answers your question.

**Comment by friendlytherapist** [comment]
Thanks, maybe consider adding this to the readme?

**Comment by fakob** [comment]
Good idea, I have added it to the readme section.
