### ISSUE TITLE
Save thumbnails timecodes ?

### ISSUE THREAD

**Issue by melMass** [fakob/MoviePrint_v004#3]
Hi Fakob,

Amazing software! 
I was wondering if there is a way to save the captured thumbnails TC's.
I'm basically iterating over the same movie, and I want to be able to extract the same thumbnails from all versions?

Is that doable right now?

Thanks

**Comment by fakob** [comment]
Hi Mel

Thanks.
Unfortunately this is currently not possible with MoviePrint. Could you
maybe describe I your use case in more detail? If that is something other
users could also benefit from, I could look into it and put it on the
roadmap.

If you only want to extract frames you could look into using the ffmpeg
command line, though I have never used it myself -
https://video.stackexchange.com/questions/19873/extract-specific-video-frames

Cheers Jakob

**Comment by melMass** [comment]
Hi Jakob,

I've been actually relying on the FFmpeg CLI for those tasks until MoviePrint (I still do in fact, but the idea of this topic is not to anymore) it is tedious and I like the visual selection of the thumbs MP offers.

What I had in mind is a way to store the TC of each thumb so that we can replace the input while keeping the exact same frames extracted.

If I'm not clear the use case could be: comparing two colour grades of the same movie.

I'm pretty sure that would not be that hard considering what MP is already capable of.

The ways this could be done is something we might discuss here.
But it might be a custom `.movieprint`file who store metadata about each frame.

What do you think?

**Comment by fakob** [comment]
Hi @melMass, a new version is out which might be of interest for you. 
I have now implemented the feature that you can easily replace a movie with another one and in addition create multiple MoviePrint edits. When replacing a movie, all MoviePrint edits you have created will then show the new movie. Try it out.
It is still not possible to save the timecodes, but I now have laid the ground work and hope that I will soon get to it.
Please let me know what you think.
[Go to new version](https://github.com/fakob/MoviePrint_v004/releases/tag/0.1.16-alpha)

**Comment by melMass** [comment]
Thanks @fakob,  thumbnail position memory is all I personally need so this is perfect! I'll try ASAP

**Comment by fakob** [comment]
The latest release now also includes the ability to store the positions in a json file or embed them in the MoviePrint itself. With `Import MoviePrint` you can recall them again.
[Go to new version](https://github.com/fakob/MoviePrint_v004/releases/tag/0.1.17-alpha)
