### ISSUE TITLE
saveThumb ("same movie location")

### ISSUE THREAD

**Issue by b1n4ryj4n** [fakob/MoviePrint_v004#4]
Hey there,
can u make pls the change that saveThumb (if i click it on the grid) uses the "same movie location" too if it's checked?

i tried for myself editing line 151 in ThumbGrid.js to use a spezific "saveToFolder" location but it does sadly not work -.-

greetz

**Comment by fakob** [comment]
Hi b1n4ryj4n
This should resolve the issue. I was working on something related so it was an easy fix.
Cheers
Jakob

**Comment by b1n4ryj4n** [comment]
Ty for the quick fix, i could not way to use this, so i compiled it myself and it works fine.

Awesome App!
Saves me a lot of time to create thumbnails.
