### ISSUE TITLE
Cannot open application

### ISSUE THREAD

**Issue by liangshuocj** [fakob/MoviePrint_v004#8]
Process:               MoviePrint_v004 [22299]
Path:                  /Applications/MoviePrint_v004.app/Contents/MacOS/MoviePrint_v004
Identifier:            com.fakob.movieprint
Version:               0.2.12 (0.2.12)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           MoviePrint_v004 [22299]
User ID:               501

Date/Time:             2020-02-18 20:41:12.695 +0800
OS Version:            Mac OS X 10.15.1 (19B88)
Report Version:        12
Bridge OS Version:     4.1 (17P1081)
Anonymous UUID:        B98AB21A-6A96-7A72-C20B-466E652DCB81

Sleep/Wake UUID:       1A9FEA0E-E8CE-40B7-8A67-4E0CD4D1D122

Time Awake Since Boot: 230000 seconds
Time Since Wake:       5000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Applications/MoviePrint_v004.app/Contents/MacOS/MoviePrint_v004
  Reason: no suitable image found.  Did find:
	/Applications/MoviePrint_v004.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
	/Applications/MoviePrint_v004.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=1

Binary Images:
       0x10c5de000 -        0x10c5deffb +com.fakob.movieprint (0.2.12 - 0.2.12) <6E272AEB-51ED-363B-B2D0-1E8B0C094EDF> /Applications/MoviePrint_v004.app/Contents/MacOS/MoviePrint_v004
       0x112b5c000 -        0x112becb5f  dyld (733.6) <DAFEA246-2F9A-3DCB-A37C-4246D4F92770> /usr/lib/dyld
    0x7fff372b8000 -     0x7fff372b8fff  com.apple.Cocoa (6.11 - 23) <EB4AD4EA-3212-385A-876E-9F8B30F8CA56> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff3a8e4000 -     0x7fff3acabff4  com.apple.Foundation (6.9 - 1673.126) <470C2315-3047-39BB-BB6B-2C620087091C> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff3b021000 -     0x7fff3b0c4ffb  com.apple.framework.IOKit (2.0.2 - 1726.41.1) <FBB4A97B-D7CF-3B8C-932D-672343D63260> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff4486c000 -     0x7fff44bb2ff6  com.apple.security (7.0 - 59306.41.2) <FB3774D5-C940-35FB-960A-86253A01BDAE> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff45a26000 -     0x7fff45a90ff7  com.apple.SystemConfiguration (1.19 - 1.19) <A52A533D-DA25-3607-A18E-CA7C539E1C52> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration

Model: MacBookPro15,1, BootROM 1037.40.124.0.0 (iBridge: 17.16.11081.0.0,0), 6 processors, 6-Core Intel Core i7, 2.2 GHz, 16 GB, SMC 
Graphics: kHW_IntelUHDGraphics630Item, Intel UHD Graphics 630, spdisplays_builtin
Graphics: kHW_AMDRadeonPro555XItem, Radeon Pro 555X, spdisplays_pcie_device, 4 GB
Memory Module: BANK 0/ChannelA-DIMM0, 8 GB, DDR4, 2400 MHz, SK Hynix, -
Memory Module: BANK 2/ChannelB-DIMM0, 8 GB, DDR4, 2400 MHz, SK Hynix, -
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x7BF), wl0: Oct 19 2019 15:33:10 version 9.113.2.0.32.5.39 FWID 01-5eb3e1fa
Bluetooth: Version 7.0.1f1, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.1 Bus
USB Device: Apple T2 Bus
USB Device: Touch Bar Backlight
USB Device: Touch Bar Display
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Headset
USB Device: Ambient Light Sensor
USB Device: FaceTime HD Camera (Built-in)
USB Device: Apple T2 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 47.3
Thunderbolt Bus: MacBook Pro, Apple Inc., 47.3

**Comment by fakob** [comment]
Hi @liangshuocj 
What application are you using to unzip? 
Please try the following
* Unpack the zip file with Macs original Archive Utility (via ‘open with’ menu)
* Or install MoviePrint via the dmg installer instead of the zip file. I have one from version 0.2.11 - https://github.com/fakob/MoviePrint_v004/releases/download/0.2.11/MoviePrint_v004-0.2.11.dmg

After starting MoviePrint do Menu -> View -> Reset application

**Comment by liangshuocj** [comment]
Thanks, I downloaded this just fine:https://github.com/fakob/MoviePrint_v004/releases/download/0.2.11/MoviePrint_v004-0.2.11.dmg

I downloaded this before: https://github.com/fakob/MoviePrint_v004/releases/download/0.2.13-beta/MoviePrint_v004-0.2.13-beta-mac.zip
Double-click the decompressed
